issuer: https://accounts.google.com
# vaikas-gh-pr-val@vaikas-chainguard-dev.iam.gserviceaccount.com
subject: "102678112892415745640"

permissions:
  pull_requests: read
  contents: read
  checks: write
