issuer: https://accounts.google.com
# mgreau85-gh-pr-val@mgreau85-chainguard.iam.gserviceaccount.com
subject: "112633836385884864874"

permissions:
  # Read PR details
  pull_requests: read
  # Read repo contents
  contents: read

