issuer: https://accounts.google.com
# vaikas-afx@vaikas-chainguard-dev.iam.gserviceaccount.com
subject: "109813338353435768951"

permissions:
  # to update PR titles and descriptions
  pull_requests: write
  contents: read
  checks: write
