issuer: https://accounts.google.com
# vaikas-gh-pr-afx@vaikas-chainguard-dev.iam.gserviceaccount.com
subject: "102739638394825949339"

permissions:
  # to update PR titles and descriptions
  pull_requests: write
  contents: read
  checks: write
